version: '3.4'

x-env: &x-env
  DB_HOST: db
  DB_PORT: 3306
  DB_USER: osuweb
  DB_PASS: ''
  DB_DATABASE: osu
  BEATMAPS_DIR: beatmaps
  MODE: 0
  THREADS: 8

services:
  diffcalc:
    image: microsoft/dotnet:sdk
    volumes:
      - .:/data
    environment:
      <<: *x-env
      DOCKER: 1
    working_dir: /data
    command: [ './docker/run.sh' ]